#!/usr/bin/env bash


export PATH="${PATH}:$HOME/.local/bin"

#1080p no selection
#twist.moe(500mb)
#tenshi.moe
#vidstream (300mb)

#selection doesnt always work but it works
#animefreak 

#too much error / not found (dont use this)
#animekisa 
#animeout(downloads twice ,should i work on it?)

# to get the highest episode number
# ls folder | grep -Eo '[0-9]{1,4}.mp4' | sed 's/\..*$//' | cut -d: -f 2 | sort -n | tail -n 1



export PATH="${PATH}:$HOME/.local/bin"

#hero successor
#youtube-dl -ci -f 'bestvideo[height=1080]+bestaudio/best' --write-sub --embed-subs --yes-playlist -o "/home/venerable_white/Videos/Anime/Airing/hero_successor/%(title)s.%(ext)s" --download-archive dl.txt https://www.youtube.com/playlist\?list\=PLwLSw1_eDZl0KbQlqHjTn5dWFSadUHkzh


#boku_no hero 5
anime dl -c 1 -p animesimple -e $((1+$(cat  /mnt/media_m/Anime/Airing/Boku_no_hero_5/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/Boku_no_hero_5 'boku no hero academia 5'

#koikimo
anime dl -c 1 -p vidstream -e $((1+$(cat  /mnt/media_m/Anime/Airing/koikimo/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/koikimo 'Koi to Yobu ni wa Kimochi Warui'

#higehiro
anime dl -c 1 -p vidstream -e $((1+$(cat  /mnt/media_m/Anime/Airing/higehiro/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/higehiro 'Hige wo Soru. Soshite Joshikousei wo Hirou.'

#fumetsu no anata
anime dl -c 1 -p vidstream -e $((1+$(cat  /mnt/media_m/Anime/Airing/fumetsu/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/fumetsu 'fumetsu no'

#vivy's song
anime dl -c 1 -p vidstream -e $((1+$(cat  /mnt/media_m/Anime/Airing/vivy/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/vivy 'vivy'


/bin/sh /home/venerable_white/.config/bspwm/bin/anime-episode-notification

/bin/sh /home/venerable_white/.config/bspwm/bin/anime-episode-count
