#!/usr/bin/env bash

#1080p no selection
#twist.moe(500mb)
#tenshi.moe
#vidstream (300mb)

#selection doesnt always work but it works
#animefreak 

#too much error / not found (dont use this)
#animekisa 
#animeout(downloads twice ,should i work on it?)

# to get the highest episode number
# ls folder | grep -Eo '[0-9]{1,4}.mp4' | sed 's/\..*$//' | cut -d: -f 2 | sort -n | tail -n 1


#jujutsu-kaisen
anime dl -c 1 -e $((1+$(cat /mnt/media_m/Anime/Airing/jujutsu_kaisen/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/jujutsu_kaisen 'jujutsu-kaisen' 

#horimiya
anime dl -c 1 -e $((1+$(cat /mnt/media_m/Anime/Airing/Horimiya/episode.txt))):  --download-dir /mnt/media_m/Anime/Airing/Horimiya 'horimiya'


#mushoku tensei
anime dl -c 1 -e $((1+$(cat /mnt/media_m/Anime/Airing/mushoku_tensei/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/mushoku_tensei 'mushoku tensei'

#tensei shitara
anime dl -e $((1+$(cat /mnt/media_m/Anime/Airing/tensei_shitara_slime_2nd_season/episode.txt))): 'https://animekisa.tv/tensei-shitara-slime-datta-ken-2nd-season' --download-dir /mnt/media_m/Anime/Airing/tensei_shitara_slime_2nd_season


#log horizon
anime dl -c 4 -p vidstream -e $((1+$(cat /mnt/media_m/Anime/Airing/log_horizon/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/log_horizon 'log horizon'


#wonder egg priority
anime dl -c 1 -p vidstream -e $((1+$(cat /mnt/media_m/Anime/Airing/wonder_egg/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/wonder_egg 'wonder egg priority'




#sasageyo
anime dl -c 1 -p vidstream -e $((1+$(cat /mnt/media_m/Anime/Airing/shingeki_no_kyojin/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/shingeki_no_kyojin/ 'shingeki no kyojin final'

#warrior -of qin
youtube-dl -ci -f 'bestvideo[height=1080]+bestaudio/best' --write-sub --embed-subs --yes-playlist  -o "/mnt/media_m/Anime/Airing/warrior_of_qin/%(title)s.%(ext)s" --download-archive dl.txt 'https://www.youtube.com/playlist?list=PLBakWosU0sfi84psQjXASSl5-usIkb4aV' 
#heaven official
youtube-dl -ci -f 'bestvideo[height=1080]+bestaudio/best' --write-sub --embed-subs --yes-playlist  -o "/mnt/media_m/Anime/Airing/heaven_official/%(title)s.%(ext)s" --download-archive dl.txt 'https://www.youtube.com/playlist?list=PLBakWosU0sfj1vJbqmi-Eyh3rjfEOvQGX' 

#re zero
anime dl -c 5 -p animefreak -e $((1+$(cat /mnt/media_m/Anime/Airing/re_zero_2_part_2/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/re_zero_2_part_2 're zero'



#i am a spider

youtube-dl -ci -f 'bestvideo[height=1080]+bestaudio/best' --write-sub --embed-subs --yes-playlist  -o "/mnt/media_m/Anime/Airing/spider_desu_ka/%(title)s.%(ext)s" --download-archive dl.txt 'https://www.youtube.com/playlist?list=PLxSscENEp7Jh0Urq4XJv3SkmYTq-goyCo' 



/bin/sh /home/venerable_white/.config/bspwm/bin/anime-episode-count