#!/usr/bin/env bash

cd /mnt/media_m/Anime/Airing/

for d in ./*/ 
do
	(cd "$d" && 
    a=$(ls | grep -Eo '[0-9]{1,4}.mp4' | sed 's/\..*$//' | cut -d: -f 2 | sort -n | tail -n 1) 
    if [[ ! -z $a ]]; then
    	if [[ "$a" -gt $(cat episode.txt) ]]; then
    		notify-send -t 15000 --icon=video-television "$d"  
    		sleep 2s
    	fi
    fi)
done
