#!/usr/bin/env bash


export PATH="${PATH}:$HOME/.local/bin"

#1080p no selection
#twist.moe(500mb)
#tenshi.moe
#vidstream (300mb)

#selection doesnt always work but it works
#animefreak 

#too much error / not found (dont use this)
#animekisa 
#animeout(downloads twice ,should i work on it?)

# to get the highest episode number
# ls folder | grep -Eo '[0-9]{1,4}.mp4' | sed 's/\..*$//' | cut -d: -f 2 | sort -n | tail -n 1



export PATH="${PATH}:$HOME/.local/bin"


#horimiya
anime dl -c 1 -e $((1+$(cat /mnt/media_m/Anime/Airing/Horimiya/episode.txt))):  --download-dir /mnt/media_m/Anime/Airing/Horimiya 'horimiya'



#tensei shitara
anime dl -e $((1+$(cat /mnt/media_m/Anime/Airing/tensei_shitara_slime_2nd_season/episode.txt))): 'https://animekisa.tv/tensei-shitara-slime-datta-ken-2nd-season' --download-dir /mnt/media_m/Anime/Airing/tensei_shitara_slime_2nd_season


#log horizon
#anime dl -c 4 -p vidstream -e $((1+$(cat /mnt/media_m/Anime/Airing/log_horizon/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/log_horizon 'log horizon'


#wonder egg priority
anime dl -c 1 -p vidstream -e $((1+$(cat /mnt/media_m/Anime/Airing/wonder_egg/episode.txt))): --download-dir /mnt/media_m/Anime/Airing/wonder_egg 'wonder egg priority'




#sasageyo
anime dl -c 1 -p tenshi.moe -e $((1+$(cat /mnt/media_m/Anime/Airing/shingeki_no_kyojin/episode.txt))): --download-dir  /mnt/media_m/Anime/Airing/shingeki_no_kyojin/ 'shingeki no kyojin final'





/bin/sh /home/venerable_white/.config/bspwm/bin/anime-episode-notification

/bin/sh /home/venerable_white/.config/bspwm/bin/anime-episode-count
