#!/usr/bin/env bash

function anime_episode_notification(){

for d in /mnt/media_m/Anime/Airing/*/ 
do
	(cd "$d" && 
    a=$(ls -lt --time=birth | awk '{for(i=9;i<=NF;i++) printf $i" "; print ""}' |  sed 's/episode.txt//g' | sed "/Preview/d" | sed "/PV/d" | sed -r '/^\s*$/d' | head -n 1)
    e=$(guessit "$a" | grep '"episode":' | awk '{print $NF}' | sed 's/,//g')
    if [ ! -z "$e" ]; then
        if [ "$e" -gt $(cat episode.txt) ] || [ ! -f episode.txt ]; then
            f=$(basename $d)
            dunstify "$f" "New episode $e" -i "~/.config/dunst/icon/love.png" -t 5000  
    		echo "$e">episode.txt
    	fi
    fi)
done
}

while true
do 
    time=$(date +%H%M)
    if [ $time -gt 2000 ]
    then
        bspc desktop -f '^1'
        kitty -e anime-downloader
        anime_episode_notification
        sleep 1.5h
    fi
    sleep 30m
 done
