#!/usr/bin/env bash

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin


bspc desktop -f '^1'

eval "export $(egrep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pgrep -u $LOGNAME bspwm)/environ)"

notify-send -t 15000 --icon=video-television "downloading anime"  


/usr/bin/kitty -e /home/venerable_white/.config/bin/anime-downloader

notify-send -t 9000 --icon=video-television "finished downloading anime" 
sleep 4s 

