#!/bin/bash

source "`ueberzug library`"

COVER="/mnt/media_m/Music/temp/album_cover.jpg"

function add_cover {
  ImageLayer::add [identifier]="img" [x]="0" [y]="0" [path]="$COVER"
}

ImageLayer 0< <(
while inotifywait -q -q -e close_write "$COVER"; do
  add_cover
done
)

