#!/bin/bash

bspc desktop -f '^5'

#terminator --new-tab -e gotop &
kitty -e htop &
sleep 300 &
kitty -e nvtop &
sleep 300 &
kitty -e sudo bandwhich &
sleep 300 &
kitty -e sudo ps_mem -w 1 &
#working except neofetch
