#!/bin/bash

bspc desktop -f '^5'

#terminator --new-tab -e gotop &
alacritty -e htop &
sleep 300 &
alacritty -e nvtop &
sleep 300 &
alacritty -e sudo bandwhich &
sleep 300 &
alacritty -e sudo ps_mem -w 1 &
#working except neofetch
