#!/bin/bash



mkdir -p /mnt/downloads/{torrents,images,pdf,archives,apk,codes,subtitle,videos}                       
                                                                                              
cd /mnt/downloads/                                                                            

#images
for i in *.svg *.jpeg *.jpg *.png *.gif *.webp; do mv -- "$i" "images/$i" ;done

#torrents
for i in *.torrent;do mv -- "$i" "torrents/$i" ;done

#pdf
for i in *.epub *.yaml *.pdf *.csv *.docx *.djvu *.html *.xml *.txt;do mv -- "$i" "pdf/$i" ;done

#archives
for i in *.tar.xz *.tar.gz *.rar *.zip *.xml.gz *.iso; do mv -- "$i" "archives/$i" ;done

#apk

for i in *.apk *.AppImage;do mv -- "$i" "apk/$i" ;done

# codes
for i in *.cpp *.jl *.c *.sh *.pt *.h5 *.php *.caffemodel *.py *.ipynb ;do mv -- "$i" "codes/$i" ;done

#videos
for i in *.mp4 *.mkv *.webm;do mv -- "$i" "videos/$i" ;done

#Subtitle

for i in *.srt ;do mv -- "$i" "subtitle/$i" ;done
