#!/bin/bash

rm -rf ~/Notes/tmp/today.txt
rm -rf ~/Notes/tmp/temp_sort.txt

mkdir -p ~/Notes/tmp

today=$(cat ~/Notes/todo.txt | awk '/TODAY/,/END/')
today_stream=$(echo "$today" | sed '/^$/d' | sed '1d; $d' | sed 's/^[0-9]. //g')
echo "$today_stream" > ~/Notes/tmp/today.txt
weekday=$(date +"%A") 
up_weekday=$(echo "$weekday" | tr '[:lower:]' '[:upper:]')

if grep -Fxq "$up_weekday" ~/Notes/todo.txt
then
    weekday_task=$(cat ~/Notes/todo.txt | awk "/$up_weekday/,/END/")
    weekday_task_stream=$(echo "$weekday_task" | sed '/^$/d' | sed '1d; $d' |sed 's/^[0-9]. //g')
    while IFS= read -r line
    do
        echo "$line" >> ~/Notes/tmp/today.txt
    done <<< "$weekday_task_stream"
fi

if grep -Fxq "EVERYDAY" ~/Notes/todo.txt
then
    everyday_task=$(cat ~/Notes/todo.txt | awk '/EVERYDAY/,/END/')
    everyday_task_stream=$(echo "$everyday_task" | sed '/^$/d' | sed '1d; $d' |sed 's/^[0-9]. //g')
    while IFS= read -r line
    do
        echo "$line" >> ~/Notes/tmp/today.txt
    done <<< "$everyday_task_stream"
fi

if [ -s ~/Notes/tmp/today.txt ]
then
     notify=$(cat ~/Notes/tmp/today.txt | sed '/^$/d') 
     while IFS= read -r line
     do
         dunstify -a "Notes" "$line" -i "~/.config/dunst/icon/work.jpg" -t 45000
     done <<< "$notify"
else
     dunstify -a "Notes" "No task for today" -i "~/.config/dunst/icon/love.png"
fi

