#!/bin/bash

while true
do
    primary=$(cat ~/Notes/today.txt | grep -oP ".*\s+\d+:\d+(?:am|pm)")
    sorted=""
    while read -r line
    do
        data=$(echo "$line" | grep -oP "\d+:\d+(?:am|pm)")
        new=$(date --date="$data" +%s)
        destro=$(echo "$line" | sed -e "s/\s\+\([0-9]\+:[0-9]\+\(am\|pm\)\)//" -e "s/^/$new /")
        sorted=$(echo -e "$sorted\n$destro")
    done <<< "$primary"

    sorted=$(echo "$sorted" | sort -k1)
    time=$(date +"%I:%M%P")
    cur_time_epoch=$(date --date="$time today" +%s)
    while read -r line
    do
        ex_time=$(echo "$line" | awk '{print $1}')
        difference=$((cur_time_epoch-ex_time))
        diff=$(echo "$difference" | sed 's/^-//g')
        if [ "$diff" -lt 900 ]
        then
            notify=$(echo $line | sed "s/$ex_time //g")
            dunstify -a "Notes" "$notify" -u "critical" -t 45000
        fi
    done <<< "$sorted"
    sleep 5s
done

