#!/bin/bash

rm -rf /tmp/today.txt
rm -rf /tmp/temp_sort.txt

today=$(cat ~/Notes/todo.txt | awk '/TODAY/,/END/')
today_stream=$(echo "$today" | sed '/^$/d' | sed '1d; $d' | sed 's/^[0-9]. //g')
echo "$today_stream" > /tmp/today.txt
weekday=$(date +"%A") 
up_weekday=$(echo "$weekday" | tr '[:lower:]' '[:upper:]')

if grep -Fxq "$up_weekday" ~/Notes/todo.txt
then
    weekday_task=$(cat ~/Notes/todo.txt | awk "/$up_weekday/,/END/")
    weekday_task_stream=$(echo "$weekday_task" | sed '/^$/d' | sed '1d; $d' |sed 's/^[0-9]. //g')
    while IFS= read -r line
    do
        echo "$line" >> /tmp/today.txt
    done <<< "$weekday_task_stream"
fi

if grep -Fxq "EVERYDAY" ~/Notes/todo.txt
then
    everyday_task=$(cat ~/Notes/todo.txt | awk '/EVERYDAY/,/END/')
    everyday_task_stream=$(echo "$everyday_task" | sed '/^$/d' | sed '1d; $d' |sed 's/^[0-9]. //g')
    while IFS= read -r line
    do
        echo "$line" >> /tmp/today.txt
    done <<< "$everyday_task_stream"
fi

primary=$(cat /tmp/today.txt | grep "at")
while IFS= read -r line
do
  data=$(echo "$line" | awk '{print $NF}')
  new=$(date -d"$data" +%H%M)
  destro=$(echo "$line" | sed -e "s/^/$new /")
  echo "$destro" >> /tmp/temp_sort.txt
done <<< "$primary"

if [ -s /tmp/today.txt ]
then
     while read line
     do
         dunstify -a "Notes" "$line" -i "~/.config/dunst/icon/work.jpg" -t 45000
     done < /tmp/today.txt
else
     dunstify -a "Notes" "No task for today" -i "~/.config/dunst/icon/love.png"
fi

