#!/bin/bash 

#dotfiles
for i in animdl broot bspwm dunst flameshot gtk-2.0 gtk-3.0 gtk-4.0 kitty lf matplotlib mirage mpd mpv ncmpcpp networkmanager-dmenu nvim pcmanfm picom polybar qt5ct qutebrowser ranger rofi startpage-browser sxhkd transmission tridactyl zathura  
do  \cp -r -u -v ~/.config/"$i"/. /mnt/media_m/git_update_config/Marble/"$i"
done

for i in mimeapps.list okularrc okularpartrc QtProject.conf sxhkhm.ini user-dirs.dirs user-dirs.locale 
do \cp -r -u -v ~/.config/"$i" /mnt/media_m/git_update_config/Marble/"$i"
done

rm -rf /mnt/media_m/git_update_config/Marble/anime-downloader/watch.json
rm -rf /mnt/media_m/git_update_config/Marble/mpd/{mpd.db,mpd.log,mpd.pid,mpdstate}
rm -rf /mnt/media_m/git_update_config/Marble/mpv/{watch_later,mpvhistory.log}

\cp -r -v  ~/.Xresources /mnt/media_m/git_update_config/Marble/ 
#cp -r -u -v ~/.oh-my-zsh /mnt/work/git/dotfiles/zsh-config/
\cp -r -v  ~/.zshrc /mnt/media_m/git_update_config/Marble/ 
\cp -r -v  ~/.zsh /mnt/media_m/git_update_config/Marble/ 

rm -rf /mnt/media_m/git_update_config/Marble/.zsh/history

rm -rf /mnt/media_m/git_update_config/Marble/qutebrowser/backup
rm -rf /mnt/media_m/git_update_config/Marble/transmission/{torrents,blocklists,resume}

#bin 
\cp -r -v ~/.config/bin/* /mnt/media_m/git_update_config/bin/ 

# various-files
\cp -r -u -v ~/sugar_level_tracker_cli/sugar_chart.csv /mnt/work/git/various-files/
\cp -r -u -v ~/sugar_level_tracker_cli/sugar_chart.pdf /mnt/work/git/various-files/

now=$(date +"%m_%d_%Y")

mkdir -p /mnt/media_m/git_update_config/various-files/{Installed-lists,firefox-css}

yay -Qe | awk '{print $1}' > /mnt/media_m/git_update_config/various-files/Installed-lists/installed_crr_$now.txt

pip freeze > /mnt/media_m/git_update_config/various-files/Installed-lists/python_installed_$now.txt

cp /home/venerable_white/installed_app_list/App_list.ipynb /mnt/media_m/git_update_config/various-files/Installed-lists/

cp -r -u -v ~/{.sfeed,.zsh,.oh-my-zsh,Bookmarks,.bash_history,.bash_logout,.bashrc,.zshrc} /mnt/media_m/git_update_config/various-files/ 
mkdir -p /mnt/media_m/git_update_config/various-files/etc/{default,X11/xorg.conf.d}
cp -r -u -v /etc/default/grub /mnt/media_m/git_update_config/various-files/etc/default/grub
cp -r -u -v /etc/X11/xorg.conf.d /mnt/media_m/git_update_config/various-files/etc/X11/
cp -r -u -v /etc/{pacman.conf,makepkg.conf} /mnt/media_m/git_update_config/various-files/etc/ 
cp -r -u -v ~/.mozilla/firefox/sfnojran.default-beta/chrome /mnt/media_m/git_update_config/various-files/firefox-css/
#cp -r -u -v /mnt/work/git/{after_base_1.txt,base-uefi.sh,curr_23_sep.txt,fresh_packages_from_ef.txt} /mnt/work/git/various-files/Installed-lists





