#!/usr/bin/env bash

git-folder-clean

git-copy-configs

cd /mnt/work/git

time=$(date +%a:%d:%h:%H:%m)

for d in ./*/ 
do
	(cd "$d" && git add . && git commit -m "regular_update-$time" && git push -u origin)
done
