#!/bin/bash 

#dotfiles


for i in alacritty anime-downloader bin bspwm dunst flameshot gtk-2.0 gtk-3.0 mpv  pcmanfm picom neofetch polybar qt5ct qutebrowser rofi sxhkd terminator zathura ranger kitty ncmpcpp newboat  sfeed transmission mpd 
do  cp -r -u -v ~/.config/"$i"/. /mnt/work/git/dotfiles/"$i"
done
 cp -p ~/.config/nvim/init.vim /mnt/work/git/dotfiles/nvim/
 cp -p ~/.config/nvim/init.vim /mnt/work/git/marble/nvim/
 cp -r -u -v ~/.config/mimeapps.list /mnt/work/git/dotfiles/
 cp -r -u -v ~/.config/okularrc /mnt/work/git/dotfiles/
 cp -r -u -v ~/.config/okularpartrc /mnt/work/git/dotfiles/
 cp -r -u -v ~/.Xresources /mnt/work/git/dotfiles/
 cp -r -u -v ~/.Xresources /mnt/work/git/marble/

cp -r -u -v /home/venerable_white/startpage-browser /mnt/work/git/marble/
cp -r -u -v /home/venerable_white/startpage-browser /mnt/work/git/dotfiles/


 cp -r -u -v ~/.config/bin/* /mnt/work/git/bin/

\cp -r -u -v ~/sugar_level_tracker_cli/sugar_chart.csv /mnt/work/git/various-files/
\cp -r -u -v ~/sugar_level_tracker_cli/sugar_chart.pdf /mnt/work/git/various-files/

now=$(date +"%m_%d_%Y")

mkdir /mnt/work/git/various-files/Installed-lists

yay -Qe | awk '{print $1}' > /mnt/work/git/various-files/Installed-lists/installed_crr_$now.txt

pip freeze > /mnt/work/git/various-files/Installed-lists/python_installed_$now.txt

cp /home/venerable_white/installed_app_list/App_list.ipynb /mnt/work/git/various-files/Installed-lists/


for i in bin bspwm dunst gtk-2.0 gtk-3.0 kitty mpd ncmpcpp nvim pcmanfm picom polybar qt5ct qutebrowser ranger rofi startpage-browser sxhkd zathura 
do  cp -r -u -v ~/.config/"$i"/. /mnt/work/git/marble/"$i"
done

cp -r -u -v ~/.oh-my-zsh /mnt/work/git/marble/
cp -r -u -v ~/.zshrc /mnt/work/git/marble/
cp -r -u -v ~/.zsh /mnt/work/git/marble/

cp -r -u -v ~/{.sfeed,.zsh,.oh-my-zsh,Bookmarks,startpage-browser,.bash_history,.bash_logout,.bashrc,.zshrc} /mnt/work/git/various-files/
cp -r -u -v /etc/default/grub /mnt/work/git/various-files/
cp -r -u -v /etc/X11/xorg.conf.d /mnt/work/git/various-files/
cp -r -u -v /etc/{pacman.conf,makepkg.conf} /mnt/work/git/various-files/
cp -r -u -v ~/.mozilla/firefox/sfnojran.default-beta/chrome /mnt/work/git/various-files/firefox-css/


rm -rf /mnt/work/git/marble/.zsh/history
rm -rf /mnt/work/git/dotfiles/mpv/watch_later
rm -rf /mnt/work/git/dotfiles/mpv/mpvhistory.log

rm -rf /mnt/work/git/dotfiles/qutebrowser/backup
rm -rf /mnt/work/git/dotfiles/transmission/torrents
rm -rf /mnt/work/git/dotfiles/transmission/blocklists
rm -rf /mnt/work/git/dotfiles/transmission/resume
rm -rf /mnt/work/git/marble/mpd/{mpd.db,mpd.log,mpd.pid,mpdstate}
#rm -rf /mnt/work/git/various-files
#mpd and others try something else

