#!/usr/bin/env bash

git-folder-clean

git-copy-configs

cd /mnt/work/git

time=$(date +%d_%h_%H:%m)

for d in ./*/ 
do
	(cd "$d" && git add . && git commit -m "updated_at_$time" && git push -u origin)
done
