#!/bin/bash


DIR="$HOME/.config/bin"

# Apps
files="Pcmanfm"
editor="Sublime -text"
disk="Gnome-Disks"
gparted="Gparted"
timeshift="Timeshift"
ranger_="Ranger"
# Variable passed to rofi
options="$files\n$editor\n$disk\n$timeshift\n$gparted\n$ranger_"

chosen="$(echo -e "$options" | rofi -dmenu -p "Run as root(#)")"
case $chosen in
    $files)
        sh $HOME/.config/bin/apps_as_root 'pcmanfm'
        ;;
    $editor)
        sh $HOME/.config/bin/apps_as_root 'subl3'
        ;;
    $disk)
        sh $HOME/.config/bin/apps_as_root 'gnome-disks'
        ;;
    $timeshift)
        sh $HOME/.config/bin/apps_as_root 'timeshift-gtk'
        ;; 
    $gparted)
        sh $HOME/.config/bin/apps_as_root 'gpartedbin'
        ;;    
    $ranger_)
        sh $HOME/.config/bin/apps_as_root 'ranger-file-manager'
        ;;
esac
#[[ -z $chosen ]] && exit
