#!/bin/bash

a=$(rofi -dmenu -p "enter sugar-level")
[[ -z $a ]] && exit

cd ~/My_sugar_level

python sugar-level.py $a

cd ..

#1. read from last line and dunstify
#2. do a backup

\cp ~/My_sugar_level/sugar_chart.csv /mnt/work/My_sugar_level/