#!/bin/bash

# Execute the Python script and store the output in a variable
output=$(python3 $HOME/.config/bin/anime_airing_date.py)

# Display the output in Rofi
echo "$output" | rofi -dmenu -i -lines 15 -width 100 -font "mono 12" -p "Next Episode Release Dates"
