#!/bin/bash

cd /mnt/study/Second_year

rofi_menu()
{
   curr_choose=$(ls -d */ *.pdf *.djvu| rofi -dmenu -p "Bookmarks:")
 }

rofi_menu
[[ -z $curr_choose ]] && exit

new_choose=$curr_choose

loop()
{
	if [[ -d $new_choose ]]; then
		cd "$new_choose"
		rofi_menu
		[[ -z $curr_choose ]] && exit
		new_choose=$curr_choose
		loop
	else 
		org.kde.okular "$new_choose"
	fi
}

loop

