#!/bin/bash

rm -rf ~/Notes/today.txt
#mkdir -p ~/Notes/tmp

weekday=$(date +"%A")
up_weekday=$(echo "$weekday" | tr '[:lower:]' '[:upper:]')

while IFS= read -r line
do
    IFS=';' read -ra parts <<< "$line"
    task_name="${parts[0]}"
    task_detail="${parts[1]}"
    task_time="${parts[2]}"
    task_day="${parts[3]:-EVERYDAY}"
    task_day="$(echo "$task_day" | tr '[:lower:]' '[:upper:]' | xargs)"

    if [[ "$task_day" == "$up_weekday" ]] || [[ "$task_day" == "EVERYDAY" ]]; then
        formatted_task=$(printf "%-20s %-30s %-10s %s\n" "${task_name}" "${task_detail}" "${task_time}" "${task_day}")
        echo "$formatted_task" >> ~/Notes/today.txt
    fi
done < ~/Notes/todo.txt

if [ -s ~/Notes/today.txt ]
then
    rofi_command="rofi -dmenu -i -p \"Today's Tasks:\" -no-custom -width 80 -format i"
    task_list=$(cat ~/Notes/today.txt | sed '/^$/d')
    selected_task=$(echo -e "${task_list}" | eval $rofi_command)

    if [ -n "$selected_task" ]; then
        selected_line=$(echo "$task_list" | sed -n "$(($selected_task + 1))p")
        echo "Selected task: $selected_line"
    fi
else
    echo "No tasks for today."
fi

