#!/bin/bash

cd ~/Bookmarks

selected=$(basename --suffix=.txt -- *.txt | rofi -dmenu -p "Bookmarks:")
[[ -z $selected ]] && exit

web_names=$(for i in $(cat "$selected".txt);do python ~/.config/bin/domain-name.py "$i"; done)

link=$(echo "$web_names" | rofi -dmenu)
[[ -z $link ]] && exit

#alink=$(cat "$selected".txt | grep "$link")

qutebrowser --target tab "$link" 

