#!/bin/bash

#name of process
a=$(rofi -dmenu -p "enter process name")
[[ -z $a ]] && exit

#name of pid of that process
b=$(ps -aux | grep "$a" | awk -v f=1 -v t=11 '{for(i=1;i<=NF;i++)if(i>=f&&i<=t)continue;else printf("%s%s",$i,(i!=NF)?OFS:ORS)}' | rofi -dmenu -p "choose process id")
[[ -z $b ]] && exit

#show process name
c=$(ps -aux | grep "$b" | grep -v grep | awk '{print $2}')
#kill process

d=$(ps -aux | grep "$c" | awk -v f=1 -v t=11 '{for(i=1;i<=NF;i++)if(i>=f&&i<=t)continue;else printf("%s%s",$i,(i!=NF)?OFS:ORS)}' )
[[ -z $d ]] && exit

basename "$d"
f="$(basename -- $d)"


kill "$c"

if [ -n "$c" ]; then
    notify-send -t 9000 --icon=video-television "killed"  "$f"
else
    notify-send -t 9000 --icon=video-television "Not a valid pid"
fi








