#!/bin/bash


a=$(rofi -theme dmenu -dmenu -p "enter sugar-level")
[[ -z $a ]] && exit


cd ~/sugar_level_tracker_cli
mkdir -p output
#write to csv
python sugar-level.py $a
#write to pdf

python latex.py
python sugar-data-analysis.py

FILE=sugar_level.png
if [ -f "$FILE" ]; then
  sed -i 's/%//g' sugar_chart.tex
fi  


pdflatex  sugar_chart.tex


#1. read from last line and dunstify
#2. do a backup

\cp {*.png,sugar_chart.pdf,sugar_chart.csv} output/

\cp $HOME/sugar_level_tracker_cli/output/* /mnt/work/My_sugar_level/
notify-send -t 9000 --icon=video-television "sugar_chart updated" 

