#!/bin/sh

sfeed_update   

cd ~/.sfeed/feeds/ || exit 1
awk -F '\t' -v "old=$(($(date +'%s') - 86400))" '
BEGIN {	OFS = "\t"; }
int($1) >= old {
$2 = "[" FILENAME "] " $2;
print $0;
}' * | \
sort -k1,1rn | \
sfeed_plain

