#!/bin/bash
bspc desktop -f '^6'

mpd_stat=$(mpc status | awk '{ print $2 }')  

if [ "$mpd_stat" == "n/a" ]; then
  sed -i 's/;//g' ~/.config/polybar/include-modules.ini 
  bspbar &
  spotify 
else
    mpc stop
    sed -i 's/;//g' ~/.config/polybar/include-modules.ini 
    bspbar &
    spotify 
fi







