#!/bin/bash

yes | yay -Scc
paccache -r

yes | yay -Rns $(yay -Qtdq)
rm -rf ~/.cache/*

rm -rf ~/.stremio-server/stremio-cache/*
rm -rf ~/.config/mpv/watch_later/*
rm -rf ~/.thumbnails/*


betterlockscreen -u ~/Pictures/wallpapers/dark/0037.jpeg 
