#!/bin/bash

#mkdir ~/tmp
#cp -r ~/.cache/p10k-* ~/tmp/
#cp -r ~/.cache/gitstatus ~/tmp/


yes | yay -Scc
paccache -r

yes | yay -Rns $(yay -Qtdq)
rm -rf ~/.cache/*

sudo rm -rf /tmp/makepkg/*

rm -rf ~/.stremio-server/stremio-cache/*
rm -rf ~/.config/mpv/watch_later/*
rm -rf ~/.thumbnails/*

#cp -r ~/tmp/*  ~/.cache/
#rm -rf ~/tmp 


betterlockscreen -u ~/Pictures/wallpapers/dark/0053.jpg 
