#!/bin/bash

pactl set-sink-volume @DEFAULT_SINK@ -5%  && dunstify -u low --replace=69 -i /usr/share/icons/HighContrast/status/24x24/audio-volume-medium.svg "Volume Down : $(~/.config/bspwm/bin/volume)%"
